Wallet-based gating of gateway
labdao/lab-exchange pull request #726
Opened 2023-10-24 12:52 UTC by acashmoney

## What type of PR is this? (check all applicable)

- [ ] 🎮 Feature
- [ ] 🐛 Bug Fix
- [ ] 🍧 Refactor
- [ ] 🔋 Optimization
- [ ] 📓 Documentation Update

## Description

_Please provide a brief description of the changes here. Include why they are needed, if applicable._

_Any demonstrations of the changes (Loom, gif, etc.) may also go here._

## Related Tickets & Documents

_Reference as needed._

## Steps to Test

_A list of steps a reviewer can walk through to test the changes._

## Relevant GIF 

_Required 🐔_

2023-10-25 12:45 UTC, acashmoney commented on go.mod
>  	github.com/syndtr/goleveldb v1.0.1-0.20210819022825-2ae1ddf74ef7 // indirect
Breaking change from `geth` dependency

2023-10-30 02:44 UTC, acashmoney commented
@thetechnocrat-dev this should be ready for review. You'll need to set the env value for `NEXT_PUBLIC_OPTIMISM_GOERLI_ALCHEMY_RPC` which I can provide.

2023-10-30 03:31 UTC, acashmoney commented
Need to figure out why CI fails. I believe it is due to the new member-only middleware for accessing flows

2023-10-31 06:29 UTC, acashmoney commented
@thetechnocrat-dev new changes are ready for review now. Of note:
- Members only middleware wrapping is now limited to just the endpoint for adding flows, since this the main cost source
- Members gating works on the frontend for flow submission - only wallets holding a Record may submit a flow
- DB migration for adding `is_member` column to users table
- Adding flow endpoint testing in CI is commented out for now - I think we should dedicate a new issue to solve this with members only middleware

2023-10-31 13:31 UTC, thetechnocrat-dev requested changes

2023-10-31 13:31 UTC, thetechnocrat-dev commented on .github/actions/gateway-tests/action.yml
> +    #     response=$(curl -s -X POST "http://localhost:8080/user" \
Do these not pass if uncommented?

2023-10-31 14:01 UTC, acashmoney commented on .github/actions/gateway-tests/action.yml
> +    #     response=$(curl -s -X POST "http://localhost:8080/user" \
@thetechnocrat-dev these fail if uncommented.

**Without add user step:** https://github.com/labdao/plex/actions/runs/6699702828/job/18204440364
**Including add user step so user persists for add flow step:** https://github.com/labdao/plex/actions/runs/6700028618/job/18205295527

2023-11-01 18:48 UTC, acashmoney commented on Dockerfile
> +
Thanks @alabdao. The ABI is currently the only non `.go` file in utils, but I agree it makes sense to copy the whole folder in case we add more in the future. 

Updated and moved the `COPY --from=builder` to line 25.

2023-11-01 20:42 UTC, thetechnocrat-dev commented on gateway/handlers/users.go
> +			IsMember      bool   `json:"isMember"`
Can this line get removed? Think IsMember is just needed in the response.

2023-11-01 20:42 UTC, thetechnocrat-dev commented on gateway/handlers/users.go
> +			// User already exists, update membership status
This should be in a user update endpoint that takes a PATCH request. Can save for a refactor or do now.

2023-11-01 21:09 UTC, thetechnocrat-dev approved these changes

2023-12-06 16:23 UTC, closed without merging